# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  before_script:
     - apt update && apt -y install cmake make
  script:
    - cmake .
    - make -j4
  artifacts:
    paths:
      - libwavespp.so
      - libwavespp.a
      - test_base58
      
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - make test