# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  before_script:
     - apt update && apt -y install cmake make rpm rpm-common
     # install waves-c
     - rm -rf src/waves-c
     - mkdir -p src/waves-c
     - cd src/waves-c
     - git clone https://git@github.com/qbcir/waves-c.git .
     - cmake -DCMAKE_BUILD_TYPE=Debug .
     - make -j4
     - make package
     - dpkg -i waves-c-*.deb
     - cd -
     # Install coda
     - mkdir -p src/coda
     - cd src/coda
     - git clone https://github.com/bachan/coda.git .
     - cmake  .
     - make package
     - dpkg -i libcoda-*.deb
     - cd -
  tags:
    - shell
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j4
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/

# run tests using the binary built before
test:
  stage: test
  tags:
    - shell
  script:
    - cd build
    - make test